[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildArgs = { DOMAIN = "${{DOMAIN}}", THUMBNAIL_SMALL_WIDTH = "${{THUMBNAIL_SMALL_WIDTH}}", THUMBNAIL_MEDIUM_WIDTH = "${{THUMBNAIL_MEDIUM_WIDTH}}", THUMBNAIL_HEIGHT_MULTIPLIER = "${{THUMBNAIL_HEIGHT_MULTIPLIER}}" }

[deploy]
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2
