[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildArgs = { EXTERN_LOCATION_IMAGES_STORAGE_PATH = "${{EXTERN_LOCATION_IMAGES_STORAGE_PATH}}", LOCAL_IMAGES_STORAGE_PATH = "${{LOCAL_IMAGES_STORAGE_PATH}}", THUMBNAIL_SMALL_WIDTH = "${{THUMBNAIL_SMALL_WIDTH}}", THUMBNAIL_MEDIUM_WIDTH = "${{THUMBNAIL_MEDIUM_WIDTH}}", THUMBNAIL_HEIGHT_MULTIPLIER = "${{THUMBNAIL_HEIGHT_MULTIPLIER}}", EXTERNAL_TO_LOCAL_PATHS_MAP = "${{EXTERNAL_TO_LOCAL_PATHS_MAP}}" }

[deploy]
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2
